version: '3'

volumes:
  data-base:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/product_register'
    environment:
      - 'DATABASE_PASSWORD=postgres'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    volumes:
      - 'data-base:/var/lib/postgresql/data'